### PR TITLE
Fix failing tests due to precision errors on arm64

### LINKED ISSUE #33: A few tests fail in different architectures due to precision errors
When running the test suite on s390x and ppc64le architectures, I get the following output:

```
go test -compiler gc -ldflags '' github.com/montanaflynn/stats
--- FAIL: TestCorrelation (0.00s)
	correlation_test.go:33: Correlation 0.9912407071619304 != 0.9912407071619302
	correlation_test.go:47: Correlation 0.9912407071619304 != 0.9912407071619302
--- FAIL: TestOtherDataMethods (0.00s)
	data_test.go:22: github.com/montanaflynn/stats.(Float64Data).Correlation-fm() => 0.2087547359760545 != 0.20875473597605448
	data_test.go:22: github.com/montanaflynn/stats.(Float64Data).Pearson-fm() => 0.2087547359760545 != 0.20875473597605448
	data_test.go:22: github.com/montanaflynn/stats.(Float64Data).Covariance-fm() => 7.381421553571428 != 7.3814215535714265
	data_test.go:22: github.com/montanaflynn/stats.(Float64Data).CovariancePopulation-fm() => 6.458743859374999 != 6.458743859374998
--- FAIL: TestLinearRegression (0.00s)
	regression_test.go:19: [{1 2.380000000000002} {2 3.080000000000001} {3 3.7800000000000002} {4 4.4799999999999995} {5 5.179999999999999}] != 2.3800000000000026
	regression_test.go:23: [{1 2.380000000000002} {2 3.080000000000001} {3 3.7800000000000002} {4 4.4799999999999995} {5 5.179999999999999}] != 3.0800000000000014
	regression_test.go:31: [{1 2.380000000000002} {2 3.080000000000001} {3 3.7800000000000002} {4 4.4799999999999995} {5 5.179999999999999}] != 4.479999999999999
	regression_test.go:35: [{1 2.380000000000002} {2 3.080000000000001} {3 3.7800000000000002} {4 4.4799999999999995} {5 5.179999999999999}] != 5.179999999999998
--- FAIL: TestLogarithmicRegression (0.00s)
	regression_test.go:94: [{1 2.152082236381168} {2 3.330555922249221} {3 4.019918836568675} {4 4.509029608117274} {5 4.8884133966836645}] != 2.1520822363811702
	regression_test.go:98: [{1 2.152082236381168} {2 3.330555922249221} {3 4.019918836568675} {4 4.509029608117274} {5 4.8884133966836645}] != 3.3305559222492214
	regression_test.go:102: [{1 2.152082236381168} {2 3.330555922249221} {3 4.019918836568675} {4 4.509029608117274} {5 4.8884133966836645}] != 4.019918836568674
	regression_test.go:106: [{1 2.152082236381168} {2 3.330555922249221} {3 4.019918836568675} {4 4.509029608117274} {5 4.8884133966836645}] != 4.509029608117273
	regression_test.go:110: [{1 2.152082236381168} {2 3.330555922249221} {3 4.019918836568675} {4 4.509029608117274} {5 4.8884133966836645}] != 4.888413396683663
FAIL
FAIL	github.com/montanaflynn/stats	0.003s
```

I also opened a similar bug report for x/image with a bug that seems to be related to this one https://github.com/golang/go/issues/21460

In addition, the tests also fail for i686 architectures, with a different output:

```
go test -compiler gc -ldflags '' github.com/montanaflynn/stats
--- FAIL: TestLogarithmicRegression (0.00s)
	regression_test.go:94: [{1 2.1520822363811654} {2 3.3305559222492205} {3 4.019918836568676} {4 4.509029608117276} {5 4.888413396683665}] != 2.1520822363811702
	regression_test.go:98: [{1 2.1520822363811654} {2 3.3305559222492205} {3 4.019918836568676} {4 4.509029608117276} {5 4.888413396683665}] != 3.3305559222492214
	regression_test.go:102: [{1 2.1520822363811654} {2 3.3305559222492205} {3 4.019918836568676} {4 4.509029608117276} {5 4.888413396683665}] != 4.019918836568674
	regression_test.go:106: [{1 2.1520822363811654} {2 3.3305559222492205} {3 4.019918836568676} {4 4.509029608117276} {5 4.888413396683665}] != 4.509029608117273
	regression_test.go:110: [{1 2.1520822363811654} {2 3.3305559222492205} {3 4.019918836568676} {4 4.509029608117276} {5 4.888413396683665}] != 4.888413396683663
FAIL
FAIL	github.com/montanaflynn/stats	0.005s
```

Note that this does not seem to be related to the issue mentioned above for x/image.

### PR DESCRIPTION
**Pull request by Gu1nness**
Co-authored-by: @nbraud
Fixes #33

### CODE REVIEW

**Comment by nbraud** [comment]
FYI, this can be tested without access to a non-amd64 machine, using `qemu-user-static`.
Just `GOARCH=arm64 go test ` will work, thanks to some `binfmt` magic.

**Comment by anthonyfok** [comment]
Thank you so much @Gu1nness and @nbraud!  This is an awesome fix to #33!

There is only one tiny thing I would recommend, and that is to run `go fmt` and push to this pull request again, and that would unify the spacing for correlation_test.go, test_utils_test.go, util.go.

Many thanks!

**Comment by nbraud** [comment]
@anthonyfok I was hoping you'd have a suggestion for a better place to put test utilities than `test_utils_test` ;3

**Comment by anthonyfok** [comment]
@nbraud Ha ha!  I didn't look too closely at the rest of the patch / pull request yet, but in my limited (and abandoned) experiment, I named it `tolerance_test.go` so it matches the main function tolerance() therein, but with the disadvantage that it looks too much like one of the other features (e.g. `variance.go` and `variance_test.go`), so your naming of `test_utils_test.go` is good that it is unambiguous.  ^_^

File: correlation_test.go [hunk 1]
```diff
@@ -8,12 +8,13 @@ import (
 	"github.com/montanaflynn/stats"
 )
 
-func ExampleCorrelation() {
+func ExampleCorrelation(l *testing.T) {
```
Comment (montanaflynn) [inline correlation_test.go:11]: This fails for older Go versions which won't accept an argument in an en Example test:

https://travis-ci.org/github/montanaflynn/stats/builds/749863684

File: correlation_test.go [hunk 2]
```diff
@@ -8,12 +8,13 @@ import (
...
 	s1 := []float64{1, 2, 3, 4, 5}
 	s2 := []float64{1, 2, 3, 5, 6}
 	a, _ := stats.Correlation(s1, s2)
-	fmt.Println(a)
-	// Output: 0.9912407071619302
+	if !veryclose(a, 0.9912407071619302) {
```
Comment (montanaflynn) [inline correlation_test.go:15]: I think we could use `stats.Round` here with the same result and added benefit of showing off another exported function instead of a private function that cannot be copy / pasted as one would expect from an example.

**Review by montanaflynn — CHANGES_REQUESTED** [review]

**Comment by montanaflynn** [comment]
Great work @Gu1nness and @nbraud, happy to see this solved!

I see it failed tests for older Go versions: https://travis-ci.org/github/montanaflynn/stats/builds/749863684 and left some comments on how I think we could fix that and improve the example at the same time.

I also agree with @anthonyfok that running `go fmt` to fix the spacing so it matches and doesn't result in the next PR having unrelated formatting changes would be good.

Once the formatting and example changes are pushed I'll be glad to merge!

**Comment by montanaflynn** [comment]
I made the changes and added tests for arm64 on travisci, and they all passed! 🎉 

I've also merged the PR into master, they will be included in a new tagged release soon.
